name: Deployment
on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    environment: Dots_and_Boxes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.5'
          cache: 'npm'
      - run: npm install

      - name: Run build
        run: npm run build --if-present

      - name: Copy dist to vps
        uses: appleboy/scp-action@master
        with:
          # Selecting all folders except "node_modules"
          source: ".,!node_modules"
          target: /var/www/Dots-and-Boxes
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - run: echo "Deployment is ${{ job.status }}."